/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Laporan;


import Dashboard.Dashboard;
import Penjualan.*;
import Pelanggan.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.config;
import GlobalVariable.UserLoginVariable;
import java.text.SimpleDateFormat;

import java.util.Date;
/**
 *
 * @author Grendy
 */
public class LaporanPenjualan extends javax.swing.JFrame {

    public UserLoginVariable userLoginData = new UserLoginVariable();
    public String sql;
    public Connection conn;
    public Statement stat;
    public ResultSet res;
    public String kategori;

    /**
     * Creates new form Users
     */
    public LaporanPenjualan() {
        initComponents();
        config konfigurasi = new config();
        konfigurasi.config();
        conn = konfigurasi.conn;
        stat = konfigurasi.stm;
        kategori = "id_penjualan";
        load_table();
    }

    public void load_table() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("No Transkasi");
        table.addColumn("Nama Produk");
        table.addColumn("Pelanggan");
        table.addColumn("User");
        table.addColumn("Harga Satuan");
        table.addColumn("Harga Total");
        table.addColumn("Jumlah");
        table.addColumn("Diskon");
        table.addColumn("Tanggal");
        try {
sql = "SELECT tb_penjualan.id_penjualan AS id_penjualan, tb_penjualan.no_transaksi AS no_transaksi, tb_produk.nama_produk AS nama_produk, " +
                         "tb_pelanggan.nama AS nama_pelanggan, tb_user.nama AS nama_user, tb_penjualan.harga_satuan AS harga_satuan, tb_penjualan.harga_total AS harga_total, " +
                         "tb_penjualan.jumlah AS jumlah, tb_penjualan.diskon AS diskon, tb_penjualan.tanggal AS tanggal " +
                         "FROM tb_penjualan " +
                         "INNER JOIN tb_produk ON tb_penjualan.id_produk = tb_produk.id_produk " +
                         "INNER JOIN tb_pelanggan ON tb_penjualan.id_pelanggan = tb_pelanggan.id_pelanggan " +
                         "INNER JOIN tb_user ON tb_penjualan.id_user = tb_user.id_user " +
                         "WHERE " + kategori + " LIKE '%" + txtCari.getText() + "%' " +
                         "ORDER BY tb_penjualan.id_penjualan ASC";
            res = stat.executeQuery(sql);
            while (res.next()) {
                table.addRow(new Object[]{
                    res.getString("id_penjualan"),
                    res.getString("no_transaksi"),
                    res.getString("nama_produk"),
                    res.getString("nama_pelanggan"),
                    res.getString("nama_user"),
                    res.getInt("harga_satuan"),
                    res.getInt("harga_total"),
                    res.getInt("jumlah"),
                    res.getInt("diskon"),
                    res.getString("tanggal"),});
            }
            tabelProduk.setModel(table);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "fail get data " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 480));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pencarian Berdasarkan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "No Transaksi", "User", "Film" }));
        cbKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKategoriItemStateChanged(evt);
            }
        });
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKategoriItemStateChanged
        switch (cbKategori.getSelectedIndex()) {
            case 0:
            kategori = "id_penjualan";
            break;
            case 1:
            kategori = "no_transaksi";
            break;
            case 3:
            kategori = "tb_user.nama";
            txtCari.setVisible(true);
            break;
            case 4:
            kategori = "tb_produk.nama_produk";
            txtCari.setVisible(true);
            break;
        }
    }//GEN-LAST:event_cbKategoriItemStateChanged

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String date = "19 Mei 2024";

        //        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        //        String tanggal = d.format(new Date());

        if (txtCari.getText().equals("")) {
            load_table();
        } else {
            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("ID");
            table.addColumn("No Transkasi");
            table.addColumn("Nama Produk");
            table.addColumn("Pelanggan");
            table.addColumn("User");
            table.addColumn("Harga Satuan");
            table.addColumn("Harga Total");
            table.addColumn("Jumlah");
            table.addColumn("Diskon");
            table.addColumn("Tanggal");
            try {
sql = "SELECT tb_penjualan.id_penjualan AS id_penjualan, tb_penjualan.no_transaksi AS no_transaksi, tb_produk.nama_produk AS nama_produk, " +
                         "tb_pelanggan.nama AS nama_pelanggan, tb_user.nama AS nama_user, tb_penjualan.harga_satuan AS harga_satuan, tb_penjualan.harga_total AS harga_total, " +
                         "tb_penjualan.jumlah AS jumlah, tb_penjualan.diskon AS diskon, tb_penjualan.tanggal AS tanggal " +
                         "FROM tb_penjualan " +
                         "INNER JOIN tb_produk ON tb_penjualan.id_produk = tb_produk.id_produk " +
                         "INNER JOIN tb_pelanggan ON tb_penjualan.id_pelanggan = tb_pelanggan.id_pelanggan " +
                         "INNER JOIN tb_user ON tb_penjualan.id_user = tb_user.id_user " +
                         "WHERE " + kategori + " LIKE '%" + txtCari.getText() + "%' " +
                         "ORDER BY tb_penjualan.id_penjualan ASC";
                res = stat.executeQuery(sql);
                while (res.next()) {
                    table.addRow(new Object[]{
                        res.getString("id_penjualan"),
                        res.getString("no_transaksi"),
                        res.getString("nama_produk"),
                        res.getString("nama_pelanggan"),
                        res.getString("nama_user"),
                        res.getString("harga_satuan"),
                        res.getString("harga_total"),
                        res.getString("jumlah"),
                        res.getString("diskon"),
                        res.getString("tanggal"),});
            }
            tabelProduk.setModel(table);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "fail get data " + e.getMessage());
        }

        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
